#!/bin/bash

set -euo pipefail

# Usage:
#   1) No args: generate Client/Development.xcconfig from .env.dev and
#               Client/Production.xcconfig from .env.prod (if files exist).
#               If only legacy .env exists, generate Client/Config.xcconfig.
#   2) With args: ./setup_client_env.sh [ENV_FILE] [OUTPUT_XCCONFIG]
#      Example: ./setup_client_env.sh .env.dev Client/Development.xcconfig

PROJECT_ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_XCCONFIG_PATH="$PROJECT_ROOT_DIR/Client/Config.xcconfig"

load_env_file() {
  [ -f "$1" ] && set -a && source "$1" && set +a
}

generate_xcconfig_from_env() {
  local env_file="$1"
  local output_xcconfig="$2"

  if [[ ! -f "$env_file" ]]; then
    echo "Skip: env file not found: $env_file" >&2
    return 0
  fi

  load_env_file "$env_file" || return 0

  local convex_url posthog_key sentry_dsn
  convex_url="${CONVEX_URL:-}"
  posthog_key="${POSTHOG_API_KEY:-}"
  sentry_dsn="${SENTRY_DSN:-}"

  local missing=()
  [[ -z "$convex_url" ]] && missing+=(CONVEX_URL)
  [[ -z "$posthog_key" ]] && missing+=(POSTHOG_API_KEY)
  [[ -z "$sentry_dsn" ]] && missing+=(SENTRY_DSN)
  if (( ${#missing[@]} > 0 )); then
    echo "Error: Missing required vars in $env_file: ${missing[*]}" >&2
    return 1
  fi

  local convex_no_scheme="$convex_url"
  convex_no_scheme="${convex_no_scheme#http://}"
  convex_no_scheme="${convex_no_scheme#https://}"

  mkdir -p "$(dirname "$output_xcconfig")"
  cat > "$output_xcconfig" <<EOF
// Generated by setup_client_env.sh — do not commit secrets
// Values are written from $env_file at generation time.

// If it's URL, don't include the http:// or https://
CONVEX_URL = $convex_no_scheme
POSTHOG_API_KEY = $posthog_key
SENTRY_DSN = $sentry_dsn
EOF
  echo "Wrote: $output_xcconfig"
}

main() {
  # With args -> explicit mapping
  if (( $# >= 1 )); then
    local env_file_arg output_arg
    env_file_arg="$1"
    output_arg="${2:-$DEFAULT_XCCONFIG_PATH}"
    # Resolve to absolute paths if relative provided
    [[ "$env_file_arg" != /* ]] && env_file_arg="$PROJECT_ROOT_DIR/$env_file_arg"
    [[ "$output_arg" != /* ]] && output_arg="$PROJECT_ROOT_DIR/$output_arg"
    generate_xcconfig_from_env "$env_file_arg" "$output_arg"
    exit $?
  fi

  # No args -> try modern multi-env mapping in Client/, fallback to legacy Client/.env
  local dev_env="$PROJECT_ROOT_DIR/Client/.env.dev"
  local prod_env="$PROJECT_ROOT_DIR/Client/.env.prod"
  local legacy_env="$PROJECT_ROOT_DIR/Client/.env"

  local did_any=0
  if [[ -f "$dev_env" ]]; then
    generate_xcconfig_from_env "$dev_env" "$PROJECT_ROOT_DIR/Client/Development.xcconfig" && did_any=1
  fi
  if [[ -f "$prod_env" ]]; then
    generate_xcconfig_from_env "$prod_env" "$PROJECT_ROOT_DIR/Client/Production.xcconfig" && did_any=1
  fi
  if (( did_any == 0 )); then
    if [[ -f "$legacy_env" ]]; then
      generate_xcconfig_from_env "$legacy_env" "$DEFAULT_XCCONFIG_PATH"
    else
      echo "Error: No Client/.env.dev, Client/.env.prod, or Client/.env found" >&2
      exit 1
    fi
  fi
}

main "$@"